version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PRISMA_USERNAME}
      - POSTGRES_PASSWORD=${PRISMA_PASSWORD}
      - POSTGRES_DB=${PRISMA_DATABASE}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    container_name: server
    depends_on:
      - postgres
    build:
      context: ../backend
    env_file:
      - ../backend/.env
    restart: unless-stopped
    ports:
      - "8000:8000"
  client:
    container_name: client
    build:
      context: ../frontend
    restart: unless-stopped
    ports:
      - "80:80"
networks:
  default:
    driver: bridge